### ISSUE TITLE
Variable Error

### ISSUE THREAD

**Issue by wyhhyw123** [jamfly/ERCNN#1]
sentence_2_embedding in forward function was not used.  Change X_2 = self.dropout(sentence_1_embedding).transpose(1, 0) to X_2 = self.dropout(sentence_2_embedding).transpose(1, 0)

**Comment by freddy5566** [comment]
oh thank you for your pointing out, I didn't notice it before

**Comment by freddy5566** [comment]
Since I don't have GPU to run experiment now, I will update result later on.

**Comment by wyhhyw123** [comment]
You used transformer as encoder. Did you compare the performance of gru based ERCNN and transformer based ERCNN?&nbsp;



---Original---

**Comment by freddy5566** [comment]
I haven't test it yet, but based on my experience usually transformer outperform RNN

**Comment by wyhhyw123** [comment]
can you provide the data after processed?

**Comment by freddy5566** [comment]
preprocessed folder contains the processed data

**Comment by wyhhyw123** [comment]
thanks



---Original---
